
services:
  app:
    container_name: ${IMAGE_REPO}-app
    restart: always
    image: cr.yandex/${CR_REGISTRY}/${IMAGE_REPO}:${RELEASE_VERSION}
    command: >
      sh -c "node ./dist/main.js"
    env_file:
      - ./.env
    environment:
      VIRTUAL_HOST: ${HOST_DOMAIN}
      LETSENCRYPT_HOST: ${HOST_DOMAIN}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
    ports:
      - '${PORT}:${PORT}'
